const koa = require('koa')
const bodyParser = require('koa-bodyparser')
const bunyanLogger = require('koa-bunyan-logger')
const compress = require('koa-compress')
const cors = require('kcors')
const Celebrate = require('celebrate')
const notFoundHandler = require('./middleware/error/notFoundHandler')
const errorHandler = require('./middleware/error/errorHandler')
const log = require('./log')
const router = require('./router')

const app = koa()

app.disable('x-powered-by')
app.use(compress())
app.use(bunyanLogger())
app.use(cors())
app.use(bodyParser())
app.use(router.routes())
app.use(router.allowedMethods())
app.use(notFoundHandler)
app.use(Celebrate.errors())
app.use(errorHandler(log))

module.exports = app
