const koa = require('koa')
const bodyParser = require('koa-bodyparser')
const koaBunyanLogger = require('koa-bunyan-logger')
const compression = require('compression')
const cors = require('cors')
const Celebrate = require('celebrate')
const notFoundHandler = require('./middleware/error/notFoundHandler')
const errorHandler = require('./middleware/error/errorHandler')
const log = require('./log')
const routes = require('./routes')

const app = koa()

app.disable('x-powered-by')
app.use(compression())
app.use(koaBunyanLogger())
app.options('*', cors())
app.use(cors())
app.use(bodyParser())
app.use(routes)
app.use(notFoundHandler)
app.use(Celebrate.errors())
app.use(errorHandler(log))

module.exports = app
